name: Create tag if there's a new Sarasa Gothic version

on:
  # runs every hour
  schedule:
    - cron: "0 * * * *"
  # allow manually trigger
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'jonz94/Sarasa-Gothic-Nerd-Fonts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_PERSONAL_ACCESS_TOKEN }}
      - name: Magic 😎
        run: |
          # Find the latest tag
          LATEST_TAG=$(curl --silent https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest | jq -r .tag_name)
          echo Latest tag of be5invis/Sarasa-Gothic is ${LATEST_TAG}

          # Check if we already have a matching tag
          if git rev-parse ${LATEST_TAG} >/dev/null 2>&1; then
            echo ${LATEST_TAG} tag exists, do nothing.
          else
            echo ${LATEST_TAG} tag does not exist, tag it to trigger next action.
            git config user.name github-actions
            git config user.email github-actions@github.com
            git tag -a ${LATEST_TAG} -m "🎉 build: release version ${LATEST_TAG}"
            git push origin --tags
          fi
