name: Generate Fonts

on:
  push:
    tags:
      - v*.*.*

jobs:
  patch1:
    if: github.repository == 'jonz94/Sarasa-Gothic-Nerd-Fonts'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles: ["fixed", "fixed-slab", "mono", "mono-slab"]
        orthographies: ["cl", "hc", "j", "k", "sc", "tc"]
        variants:
          [
            "regular",
            "italic",
            "bold",
            "bolditalic",
            "semibold",
            "semibolditalic",
            "light",
            "lightitalic",
            "extralight",
            "extralightitalic",
          ]
    env:
      NERD_FONTS_VERSION: v2.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Download latest version of Sarasa Gothic from GitHub release page
        run: |
          LATEST_TAG=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          echo Downloading Sarasa Gothic ${LATEST_TAG}
          curl -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -o sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - name: Install FontForge
        run: sudo apt install fontforge -y
      - name: Download Font Patcher
        run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERD_FONTS_VERSION}/font-patcher --output font-patcher
      - name: Download source fonts
        run: sh download-source-fonts.sh
      - name: Install configparser
        run: pip install configparser
      - run: ls -l
      - name: Patch font
        run: fontforge -script font-patcher --careful --complete --no-progressbars --quiet sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}.ttf
      - run: ls -l
      - name: Rename patched font files
        run: mv *Complete.ttf sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf
      - run: ls -l
      - name: Upload patched font
        uses: actions/upload-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  patch2:
    if: github.repository == 'jonz94/Sarasa-Gothic-Nerd-Fonts'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles: ["term", "term-slab", "gothic", "ui"]
        orthographies: ["cl", "hc", "j", "k", "sc", "tc"]
        variants:
          [
            "regular",
            "italic",
            "bold",
            "bolditalic",
            "semibold",
            "semibolditalic",
            "light",
            "lightitalic",
            "extralight",
            "extralightitalic",
          ]
    env:
      NERD_FONTS_VERSION: v2.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Download latest version of Sarasa Gothic from GitHub release page
        run: |
          LATEST_TAG=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          echo Downloading Sarasa Gothic ${LATEST_TAG}
          curl -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -o sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - name: Install FontForge
        run: sudo apt install fontforge -y
      - name: Download Font Patcher
        run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERD_FONTS_VERSION}/font-patcher --output font-patcher
      - name: Download source fonts
        run: sh download-source-fonts.sh
      - name: Install configparser
        run: pip install configparser
      - run: ls -l
      - name: Patch font
        run: fontforge -script font-patcher --careful --complete --no-progressbars --quiet sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}.ttf
      - run: ls -l
      - name: Rename patched font files
        run: mv *Complete.ttf sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf
      - run: ls -l
      - name: Upload patched font
        uses: actions/upload-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }} font
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-${{ matrix.variants }}-nerd-font.ttf

  zip:
    needs: [patch1, patch2]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        styles:
          [
            "fixed",
            "fixed-slab",
            "mono",
            "mono-slab",
            "term",
            "term-slab",
            "gothic",
            "ui",
          ]
        orthographies: ["cl", "hc", "j", "k", "sc", "tc"]
    steps:
      # start of part generated by `genereate-download-patched-fonts` script
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-regular font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-italic font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bold font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-bolditalic font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibold font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-semibolditalic font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-light font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-lightitalic font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralight font
      - uses: actions/download-artifact@master
        with:
          name: Patched sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-extralightitalic font
      # end of part generated by `genereate-download-patched-fonts` script

      - run: ls -l
      - name: Zip patched font files
        run: zip -r sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-*-nerd-font.ttf
      - run: ls -l
      - name: Upload zip
        uses: actions/upload-artifact@master
        with:
          name: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip
          path: sarasa-${{ matrix.styles }}-${{ matrix.orthographies }}-nerd-font.zip

  release:
    needs: zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - run: ls -l

      # start of part generated by `genereate-download-patched-zips` script
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-slab-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-slab-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-fixed-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-slab-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-slab-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-mono-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-slab-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-slab-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-slab-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-slab-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-slab-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-term-slab-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-gothic-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-gothic-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-gothic-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-gothic-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-gothic-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-gothic-tc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-ui-cl-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-ui-hc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-ui-j-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-ui-k-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-ui-sc-nerd-font.zip
      - uses: actions/download-artifact@master
        with:
          name: sarasa-ui-tc-nerd-font.zip
      # end of part generated by `genereate-download-patched-zips` script

      - run: ls -l
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
