name: Generate Fonts

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    if: github.repository == 'jonz94/Sarasa-Mono-TC-Nerd-Font'
    runs-on: ubuntu-latest
    env:
      NERD_FONTS_VERSION: v2.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Download latest version of Sarasa Gothic
        run: |
          LATEST_TAG=$(curl --silent https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest | jq -r .tag_name)
          echo Downloading Sarasa Gothic ${LATEST_TAG}
          curl -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -O
          7z x *.7z
      - name: Install FontForge
        run: sudo apt install fontforge -y
      - name: Download Font Patcher
        run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERD_FONTS_VERSION}/font-patcher --output font-patcher
      - name: Download source fonts
        run: sh download-source-fonts.sh
      - name: Install configparser
        run: pip install configparser
      - name: Patch fonts
        run: fontforge -script font-patcher --careful --complete --no-progressbars --quiet sarasa-mono-tc-regular.ttf
      - name: Rename patched font file
        run: mv 'Sarasa Mono TC Nerd Font Complete.ttf' Sarasa-Mono-TC-Nerd-Font-Complete.ttf
      - uses: actions/upload-artifact@master
        with:
          name: Sarasa Mono TC Nerd Font Complete
          path: Sarasa-Mono-TC-Nerd-Font-Complete.ttf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Sarasa-Mono-TC-Nerd-Font-Complete.ttf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: Sarasa Mono TC Nerd Font Complete
      - run: pwd
      - run: ls -al
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Sarasa-Mono-TC-Nerd-Font-Complete.ttf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-scoop-bucket:
    name: Update scoop bucket
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Download latest Sarasa-Mono-TC-Nerd-Font-Complete.ttf
        run: |
          LATEST_TAG=$(curl --silent https://api.github.com/repos/jonz94/Sarasa-Mono-TC-Nerd-Font/releases/latest | jq -r .tag_name)
          echo Downloading Sarasa Gothic ${LATEST_TAG}
          curl -L -O https://github.com/jonz94/Sarasa-Mono-TC-Nerd-Font/releases/download/${LATEST_TAG}/Sarasa-Mono-TC-Nerd-Font-Complete.ttf
          echo ${LATEST_TAG:1} > VERSION
      - name: update scoop bucket
        run: |
          OLD_VERSION=$(jq -r '.version' bucket/Sarasa-Mono-TC-Nerd-Font.json)
          NEW_VERSION=$(cat VERSION)
          OLD_HASH=$(jq -r '.hash' bucket/Sarasa-Mono-TC-Nerd-Font.json)
          NEW_HASH=$(sha256sum Sarasa-Mono-TC-Nerd-Font-Complete.ttf | head -c 64)
          sed -i "s/${OLD_VERSION}/${NEW_VERSION}/g" bucket/Sarasa-Mono-TC-Nerd-Font.json
          sed -i "s/${OLD_HASH}/${NEW_HASH}/g" bucket/Sarasa-Mono-TC-Nerd-Font.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bucket/Sarasa-Mono-TC-Nerd-Font.json
          git commit -m "🤖 ci: update bucket version to ${NEW_VERSION}"
          git push
