name: Generate Fonts

on:
  push:
    tags:
      - v*.*.*
  # allow manually trigger (for manually testing purpose)
  workflow_dispatch:

jobs:
  prepare:
    if: github.repository == 'jonz94/Sarasa-Mono-TC-Nerd-Font'
    runs-on: ubuntu-latest
    steps:
      - name: Download latest version of Sarasa Gothic from GitHub release page
        run: |
          LATEST_TAG=$(curl --silent https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest | jq -r .tag_name)
          echo Downloading Sarasa Gothic ${LATEST_TAG}
          curl -L https://github.com/be5invis/Sarasa-Gothic/releases/download/${LATEST_TAG}/sarasa-gothic-ttf-${LATEST_TAG:1}.7z -o sarasa-gothic-ttf.7z
      - run: ls -l
      - run: 7z x *.7z
      - run: ls -l
      - name: Upload Sarasa Mono TC fonts
        uses: actions/upload-artifact@master
        with:
          name: Sarasa Mono TC ttf
          path: sarasa-mono-tc-*.ttf

  patch:
    needs: prepare
    if: github.repository == 'jonz94/Sarasa-Mono-TC-Nerd-Font'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variants:
          [
            "regular",
            "italic",
            "bold",
            "bolditalic",
            "semibold",
            "semibolditalic",
            "light",
            "lightitalic",
            "extralight",
            "extralightitalic",
          ]
    env:
      NERD_FONTS_VERSION: v2.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Download Sarasa Gothic font ${{ matrix.variants }} from artifact
        uses: actions/download-artifact@master
        with:
          name: Sarasa Mono TC ttf
      - run: ls -l
      - name: Install FontForge
        run: sudo apt install fontforge -y
      - name: Download Font Patcher
        run: curl -L https://raw.githubusercontent.com/ryanoasis/nerd-fonts/${NERD_FONTS_VERSION}/font-patcher --output font-patcher
      - name: Download source fonts
        run: sh download-source-fonts.sh
      - name: Install configparser
        run: pip install configparser
      - run: ls -l
      - name: Patch font
        run: fontforge -script font-patcher --careful --complete --no-progressbars --quiet sarasa-mono-tc-${{ matrix.variants }}.ttf
      - run: ls -l
      - name: Rename patched font files
        run: mv *Complete.ttf sarasa-mono-tc-${{ matrix.variants }}-nerd-font.ttf
      - run: ls -l
      - name: Upload patched font
        uses: actions/upload-artifact@master
        with:
          name: Patched ${{ matrix.variants }} font
          path: sarasa-mono-tc-${{ matrix.variants }}-nerd-font.ttf

  zip:
    needs: patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: Patched regular font
      - uses: actions/download-artifact@master
        with:
          name: Patched italic font
      - uses: actions/download-artifact@master
        with:
          name: Patched bold font
      - uses: actions/download-artifact@master
        with:
          name: Patched bolditalic font
      - uses: actions/download-artifact@master
        with:
          name: Patched semibold font
      - uses: actions/download-artifact@master
        with:
          name: Patched semibolditalic font
      - uses: actions/download-artifact@master
        with:
          name: Patched light font
      - uses: actions/download-artifact@master
        with:
          name: Patched lightitalic font
      - uses: actions/download-artifact@master
        with:
          name: Patched extralight font
      - uses: actions/download-artifact@master
        with:
          name: Patched extralightitalic font
      - run: ls -l
      - name: Zip patched font files
        run: zip -r sarasa-mono-tc-nerd-font.zip sarasa-mono-tc-*-nerd-font.ttf
      - run: ls -l
      - name: Upload zip
        uses: actions/upload-artifact@master
        with:
          name: Sarasa Mono TC Nerd Font
          path: sarasa-mono-tc-nerd-font.zip

  release:
    needs: zip
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download patched fonts
        uses: actions/download-artifact@master
        with:
          name: Sarasa Mono TC Nerd Font
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sarasa-mono-tc-nerd-font.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-scoop-bucket:
    name: Update scoop bucket
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Download latest sarasa-mono-tc-nerd-font.zip
        run: |
          LATEST_TAG=$(curl --silent https://api.github.com/repos/jonz94/Sarasa-Mono-TC-Nerd-Font/releases/latest | jq -r .tag_name)
          echo "Downloading sarasa-mono-tc-nerd-font.zip (tag ${LATEST_TAG})"
          curl -L -O https://github.com/jonz94/Sarasa-Mono-TC-Nerd-Font/releases/download/${LATEST_TAG}/sarasa-mono-tc-nerd-font.zip
          echo ${LATEST_TAG:1} > VERSION
      - name: update scoop bucket
        run: |
          OLD_VERSION=$(jq -r '.version' bucket/Sarasa-Mono-TC-Nerd-Font.json)
          NEW_VERSION=$(cat VERSION)
          OLD_HASH=$(jq -r '.hash' bucket/Sarasa-Mono-TC-Nerd-Font.json)
          NEW_HASH=$(sha256sum sarasa-mono-tc-nerd-font.zip | head -c 64)
          sed -i "s/${OLD_VERSION}/${NEW_VERSION}/g" bucket/Sarasa-Mono-TC-Nerd-Font.json
          sed -i "s/${OLD_HASH}/${NEW_HASH}/g" bucket/Sarasa-Mono-TC-Nerd-Font.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bucket/Sarasa-Mono-TC-Nerd-Font.json
          git commit -m "🤖 ci: update bucket version to ${NEW_VERSION}"
          git push
